services:
  app:
    build:
      context: .
    image: crm-module-x:latest
    container_name: crm-module-x
    env_file: .env
    network_mode: host
    ports:
      - "5300:5300"
    restart: unless-stopped