export enum ErrorCodes {
    FLOW_PLATFORM_NOT_FOUND = 'FLOW_PLATFORM_NOT_FOUND',
    FLOW_PLATFORM_ALREADY_EXIST = 'FLOW_PLATFORM_ALREADY_EXIST',

    FLOW_SETTING_NOT_FOUND = 'FLOW_SETTING_NOT_FOUND',
    FLOW_SETTING_ALREADY_EXIST = 'FLOW_SETTING_ALREADY_EXIST',

    DATA_NOT_FOUND = 'DATA_NOT_FOUND',
    DATA_ALREADY_EXIST = 'DATA_ALREADY_EXIST'
}